// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SectomSharp.Data;

#nullable disable

namespace SectomSharp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250626010513_Discord-Snowflake-Id")]
    partial class DiscordSnowflakeId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SectomSharp.Data.Entities.AuditLogChannel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Id");

                    b.ToTable("AuditLogChannels");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.BotLogChannel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Id");

                    b.ToTable("BotLogChannels");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Case", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("CommandInputEmbedBuilder")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LogMessageUrl")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("LogType")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<long?>("PerpetratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("GuildId", "Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("GuildId", "PerpetratorId");

                    b.HasIndex("GuildId", "TargetId")
                        .HasDatabaseName("IX_Cases_GuildId_TargetId_Warn_Create")
                        .HasFilter("    \"LogType\" = 1 AND \"OperationType\" = 0");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Channel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Guild", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.User", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.AuditLogChannel", b =>
                {
                    b.HasOne("SectomSharp.Data.Entities.Guild", "Guild")
                        .WithMany("AuditLogChannels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.BotLogChannel", b =>
                {
                    b.HasOne("SectomSharp.Data.Entities.Guild", "Guild")
                        .WithMany("BotLogChannels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Case", b =>
                {
                    b.HasOne("SectomSharp.Data.Entities.Channel", "Channel")
                        .WithMany("Cases")
                        .HasForeignKey("ChannelId");

                    b.HasOne("SectomSharp.Data.Entities.Guild", "Guild")
                        .WithMany("Cases")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SectomSharp.Data.Entities.User", "Perpetrator")
                        .WithMany("PerpetratorCases")
                        .HasForeignKey("GuildId", "PerpetratorId");

                    b.HasOne("SectomSharp.Data.Entities.User", "Target")
                        .WithMany("TargetCases")
                        .HasForeignKey("GuildId", "TargetId");

                    b.Navigation("Channel");

                    b.Navigation("Guild");

                    b.Navigation("Perpetrator");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Channel", b =>
                {
                    b.HasOne("SectomSharp.Data.Entities.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Guild", b =>
                {
                    b.OwnsOne("SectomSharp.Data.Entities.Configuration", "Configuration", b1 =>
                        {
                            b1.Property<long>("GuildId")
                                .HasColumnType("bigint");

                            b1.HasKey("GuildId");

                            b1.ToTable("Guilds");

                            b1.ToJson("Configuration");

                            b1.WithOwner()
                                .HasForeignKey("GuildId");

                            b1.OwnsOne("SectomSharp.Data.Entities.LevelingConfiguration", "Leveling", b2 =>
                                {
                                    b2.Property<long>("ConfigurationGuildId")
                                        .HasColumnType("bigint");

                                    b2.Property<bool>("AccumulateMultipliers")
                                        .HasColumnType("boolean");

                                    b2.Property<long>("GlobalCooldown")
                                        .HasColumnType("bigint");

                                    b2.Property<double>("GlobalMultiplier")
                                        .HasColumnType("double precision");

                                    b2.Property<bool>("IsDisabled")
                                        .HasColumnType("boolean");

                                    b2.HasKey("ConfigurationGuildId");

                                    b2.ToTable("Guilds");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfigurationGuildId");

                                    b2.OwnsMany("SectomSharp.Data.Entities.LevelingRole", "AutoRoles", b3 =>
                                        {
                                            b3.Property<long>("LevelingConfigurationConfigurationGuildId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<long?>("Cooldown")
                                                .HasColumnType("bigint");

                                            b3.Property<decimal>("Id")
                                                .HasColumnType("numeric(20,0)");

                                            b3.Property<long>("Level")
                                                .HasColumnType("bigint");

                                            b3.Property<double?>("Multiplier")
                                                .HasColumnType("double precision");

                                            b3.HasKey("LevelingConfigurationConfigurationGuildId", "__synthesizedOrdinal");

                                            b3.ToTable("Guilds");

                                            b3.WithOwner()
                                                .HasForeignKey("LevelingConfigurationConfigurationGuildId");
                                        });

                                    b2.Navigation("AutoRoles");
                                });

                            b1.OwnsOne("SectomSharp.Data.Entities.WarningConfiguration", "Warning", b2 =>
                                {
                                    b2.Property<long>("ConfigurationGuildId")
                                        .HasColumnType("bigint");

                                    b2.Property<bool>("IsDisabled")
                                        .HasColumnType("boolean");

                                    b2.HasKey("ConfigurationGuildId");

                                    b2.ToTable("Guilds");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfigurationGuildId");

                                    b2.OwnsMany("SectomSharp.Data.Entities.WarningThreshold", "Thresholds", b3 =>
                                        {
                                            b3.Property<long>("WarningConfigurationConfigurationGuildId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<int>("LogType")
                                                .HasColumnType("integer");

                                            b3.Property<TimeSpan?>("Span")
                                                .HasColumnType("interval");

                                            b3.Property<int>("Value")
                                                .HasColumnType("integer");

                                            b3.HasKey("WarningConfigurationConfigurationGuildId", "__synthesizedOrdinal");

                                            b3.ToTable("Guilds");

                                            b3.WithOwner()
                                                .HasForeignKey("WarningConfigurationConfigurationGuildId");
                                        });

                                    b2.Navigation("Thresholds");
                                });

                            b1.Navigation("Leveling")
                                .IsRequired();

                            b1.Navigation("Warning")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Role", b =>
                {
                    b.HasOne("SectomSharp.Data.Entities.Guild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.User", b =>
                {
                    b.HasOne("SectomSharp.Data.Entities.Guild", "Guild")
                        .WithMany("Users")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Channel", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.Guild", b =>
                {
                    b.Navigation("AuditLogChannels");

                    b.Navigation("BotLogChannels");

                    b.Navigation("Cases");

                    b.Navigation("Channels");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SectomSharp.Data.Entities.User", b =>
                {
                    b.Navigation("PerpetratorCases");

                    b.Navigation("TargetCases");
                });
#pragma warning restore 612, 618
        }
    }
}
